In [33]:
import pandas as pd

data = pd.read_csv("home_price.csv")

In [34]:
data[['Fiyat', 'Net_Metrekare']].describe()

              Fiyat  Net_Metrekare
count  2.032600e+04   20326.000000
mean   4.649510e+06     151.964528
std    7.136120e+07    1137.304466
min    2.000000e+04       0.000000
25%    1.640000e+06      90.000000
50%    2.300000e+06     120.000000
75%    3.300000e+06     150.000000
max    7.500000e+09  110000.000000

In [35]:
data = data.drop(["Tapu_Durumu", "Takas", "Yatırıma_Uygunluk", "Eşya_Durumu"], axis=1)

In [36]:
data.head()

,Net_Metrekare,Brüt_Metrekare,Oda_Sayısı,Bulunduğu_Kat,Binanın_Yaşı,Isıtma_Tipi,Fiyat,Şehir,Binanın_Kat_Sayısı,Kullanım_Durumu,Banyo_Sayısı
0,120,150.0,4.0,4.Kat,21 Ve Üzeri,Kombi Doğalgaz,950000.0,adana,6,Boş,1.0
1,100,125.0,4.0,3.Kat,4,Kombi Doğalgaz,1250000.0,adana,10,Boş,1.0
2,89,95.0,3.0,4.Kat,0 (Yeni),Kombi Doğalgaz,1750000.0,adana,14,Boş,1.0
3,40,55.0,2.0,6.Kat,0 (Yeni),Kombi Doğalgaz,1300000.0,adana,14,Boş,1.0
4,140,150.0,4.0,Düz Giriş (Zemin),5-10,Klimalı,1700000.0,adana,4,Boş,1.0

In [37]:
data = data.drop_duplicates(keep='first')

In [38]:
data = data.dropna()

In [39]:
# data = data[data['Fiyat'] <= 20000000]

In [40]:
# 1. Domain filtering (mantık kontrolü)
data = data[data["Brüt_Metrekare"] >= data["Net_Metrekare"]]

data = data[(data["Oda_Sayısı"] >= 1) & (data["Oda_Sayısı"] <= 10)]
data = data[(data["Banyo_Sayısı"] >= 1) & (data["Banyo_Sayısı"] <= 6)]


# Net metrekareyi 30 ile 500 arası, fiyatı ise 500 bin ile 50 milyon arası sınırlama
data = data[(data['Net_Metrekare'] >= 30) & (data['Net_Metrekare'] <= 300)]
data = data[(data['Fiyat'] >= 500000) & (data['Fiyat'] <= 10000000)]

# # 2. Statistical filtering (outlier)
# for col in ["Fiyat", "Net_Metrekare"]:
#     lower = data[col].quantile(0.01)
#     upper = data[col].quantile(0.99)

#     data = data[(data[col] >= lower) & (data[col] <= upper)]

In [41]:
data['Fiyat'].max()

np.float64(10000000.0)

In [42]:
data["Fiyat"].describe()

count    1.720100e+04
mean     2.473925e+06
std      1.309284e+06
min      5.000000e+05
25%      1.600000e+06
50%      2.200000e+06
75%      3.000000e+06
max      1.000000e+07
Name: Fiyat, dtype: float64

In [43]:
data.to_csv("clean_data.csv", index=False)